### ISSUE TITLE
support data encryption in agent.properties

### ISSUE THREAD

**Issue by Larochellem** [zebrunner/carina#1054]
**Describe the bug**
You can use well the crypt feature in _config file but not Zafira file. Using it in the Zafira files does not decrypt. That's about it! Thanks!

**Comment by vdelendik** [comment]
new property file name is agent.properties

**Comment by vdelendik** [comment]
1. declare new AGENT property in R.java enum
2. as early as possible (BeforeSuite or even in CarinaListener constructor) read all agent.properties data
3. decrypt in case of any crypto pattern exists
4. declare for each property appropriate env variable with decrypted data (env vars have the highest priority for the zebrunner reporting integration.
-> verify that reporting integration works perfectly running tests from: IDE, command line, CI etc with encrypted data inside agent.properties

**Important!** it might be necessary to verify env vars in advance and don't read data from agent.properties at all if appropriate var defined

**Comment by okamara** [comment]
verified by @akamarouski
