### ISSUE TITLE
provide public and valid way of casting event firing web driver to webdriver

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1134]
everytime we do casting we reciece WebDriver object without listeners. As result we lost a lot of valuable fucntionality like logging, screenshoting etc.
The goal of the ticket investigate possibility to return WebDriver/AndroidDriver etc with all listeners

**Comment by akamarouski** [comment]
Casting drivers in 4th selenium is the wrong way to use driver functionality. Currently, drivers implement certain interfaces, using which you can check whether the driver implements certain functionality, and if necessary, use it by using the driver through the interface
You can't save event listeners when casting a driver
