### ISSUE TITLE
Implement  Page object components as Java interface 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [zebrunner/carina#1220]
**Describe the solution you'd like**
if the Page object components were implemented as a Java interface then we can have multiple interfaces describe the Page object like NavBarComponent, SearchBarComponent etc this would have 2 benefits one would automatically inherit the methods from the interface and also we can update the identifier for the element on different page objects.     

```
// Page Component
public interface ModalViewComponent extends AbstractUIObject {
   @FindBy(id = "close_icon")
    ExtendedWebElement closeButtonElement;

 default public void closeModel() {
        closeButtonElement.click();
    }

}
```

```
// Page Object 
public class WebViewPage extends WebViewPageBase implements ModalViewComponent, SearchViewComponent  {
 @FindBy(id = "close_icon2")
    ExtendedWebElement closeButtonElement;
}
```

```
// Test
public class MobileSampleTest extends MobileBaseTest {

    @Test(description = "JIRA#DEMO-0011")
    @MethodOwner(owner = "qpsdemo")
    public void testLoginUser() {
        WelcomePageBase welcomePage = initPage(getDriver(), WelcomePageBase.class);

        Assert.assertTrue(welcomePage.isPageOpened(), "Welcome page isn't opened");

        welcomePage.closeModel();
    }
}
```

**Comment by SergeiZagriychuk** [comment]
I don't think that's a good idea and we should implement it this way.
If WebViewPage implements multiple interfaces then it might be an overlapping if both of them let's assume have closeModal() method.
in my opinion what we have right now provides clearer organization of page classes and internal components

+ we couldn't use parent locators for AbstractUIObject in such case

cc @vdelendik

**Comment by vdelendik** [comment]
closing as won't fix. in addition to possible conflicts which can't be handled correctly our research showed that it is too hard to implement, i.e. there is no way to to refactor and keep old behavior. we can think about something similar for absolutely new/fresh module maybe but not for existing AbstractPage
