### ISSUE TITLE
Error : Gives wrong information in logs for copying emailable report to reports folder.

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/carina#1328]
It is related to the enhancement (https://github.com/qaprosoft/carina/issues/1254)

Even though the results are getting copied to reports folder in logs it shows below error if try to run suite via terminal/command prompt.

**mvn clean -Denv=qa -Dbrowser=chrome -Dsuite=web-test test**

2021-05-03 15:34:54 CucumberRunner [main-1] [INFO] Report json: cucumber-core-test-report.json
May 03, 2021 3:34:55 PM net.masterthought.cucumber.ReportParser parseJsonFiles
INFO: File 'target/cucumber-core-test-report.json' contains 1 features
**2021-05-03 15:34:56 Artifact [main-1] [ERROR] Failed to attach artifact reference 'Cucumber report' to test run because it has not been started yet.**

**Comment by DimaGrinevich** [comment]
Works correctly with latest carina, agent and cucumber  releases. Tested with/without zebrunner reporting and launched in ide/by maven as predeclared suite/default testng suite
