### ISSUE TITLE
investigate howto determine staled element quickly

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1370]
previous implementation was disabled as on high load waiter with 0 timeout could for for minutes...
https://github.com/qaprosoft/carina/commit/83c407eff94d3e28fab28bb0bfa09fa9a507420f#diff-522387d99dcf7b1182af5ac4365b7619d941804074f094dcd88db27ad1afb7c1R1368

to be able to react asap onto the staled elements we need one more way to make it happen. Maybe direct selenium call in try/catch or similar

**Comment by DimaGrinevich** [comment]
https://github.com/zebrunner/carina/pull/1401

**Comment by vdelendik** [comment]
completely redesigned elements manipulation making stale element too rare to handle somehow in advance.
during the testing run web and mobile tests using `7.3.15-SNAPSHOT` carina build. inside carina-demo branch `7.3.15` already use this particular core version
