### ISSUE TITLE
IAndroidUtils: make openURL call from this mobile interface in DriverHelper

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1380]
implement [todo](https://github.com/qaprosoft/carina/blob/eab53d4bf47263d6a93975f5a76b27cb672aaeb4/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java#L976)

**Comment by vdelendik** [comment]
reverted changes completely due to the complains from mobile web testing

**Comment by okamara** [comment]
verified by @akamarouski

**Comment by vdelendik** [comment]
@akamarouski, please revert changes and close as invalid request.
having this functionality as port of AnroidService or IAndroidUtils is enough. It has sense just to document that mobile related fucntionality exists and example. F.A.Q part for mobile?!

**Comment by akamarouski** [comment]
#1914

**Comment by akamarouski** [comment]
closed as  invalid request
