### ISSUE TITLE
don't catch any provider related exceptions

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1411]
we can provide s3, appcenter or azure patterns for any capabilities.app url.
there is no sense to catch any exception in case of any failure for all of them

**Comment by vdelendik** [comment]
fixed. to test just provide invalid capabilities.app reference to s3 for example for android demo test:
capabilities.app=s3://qaprosoft/carinademoexampleINVALID.apk

changes canbe tested using 7.1.9-SNAPSHOT core version

**Comment by dhreben** [comment]
Verified.
