### ISSUE TITLE
reuse new approach for testcase management keys registration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1413]
carina should follow modern zebrunner agent practice and register valid labels pers run and test instead of consolidated uuid.

instead of registration of projectid-suiteid-testcaseid as consolidated test label we have to register:
1. as test run label:
com.zebrunner.app/tcm.testrail.project-id
com.zebrunner.app/tcm.testrail.suite-id
2. as test label:
com.zebrunner.app/tcm.testrail.testcase-id

Code inside CarinaListener->attachLabels
ITestRailManager->getTestRailCasesUuid

review also qtest integration as well.

**Comment by vdelendik** [comment]
testing might be done vs `7.1.9-SNAPSHOT` or `tr-SNAPSHOT` core build.
the only difficulty is that you need valid testrail integration in the project

**Comment by dhreben** [comment]
Verified on prod. Closed.
