### ISSUE TITLE
Hiding of API request fields logic fails with blank response 

### ISSUE THREAD

**Issue by slash2020327** [zebrunner/carina#1421]
@HideRequestHeadersInLogs(headers = {"Api-Key", "Authorization"})
@HideRequestBodyPartsInLogs(paths = { "$..access_token", "$..refresh_token" })
@HideResponseBodyPartsInLogs(paths = { "$..access_token", "$..refresh_token" })
Body or header could be empty and test fails because of jsonpath path library. It would be good that the feature could skip such validation, because empty API fields are expected in some cases.

Here is stacktrace:
```
json string can not be null or empty

com.jayway.jsonpath.internal.Utils.notEmpty(Utils.java:386)
com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:36)
com.qaprosoft.carina.core.foundation.api.log.CarinaBodyPrinter.replaceValues(CarinaBodyPrinter.java:123)
com.qaprosoft.carina.core.foundation.api.log.CarinaBodyPrinter.printResponseBody(CarinaBodyPrinter.java:69)
com.qaprosoft.carina.core.foundation.api.log.CarinaResponseBodyLoggingFilter.filter(CarinaResponseBodyLoggingFilter.java:44)
```

**Comment by vdelendik** [comment]
fix might be tested using 7.1.9-SNAPSHOT core build.
@SergeiZagriychuk, provide test scenario or test on your own please and confirm that everything as expected.
