### ISSUE TITLE
provide idleTimeout capability as integer

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1433]
For example browserstack declare it as integer so carina should explicitly convert to the number as well:
![image](https://user-images.githubusercontent.com/4551455/128516965-2d4f06dd-fe22-4e77-8d64-f8f731458f48.png)

P.S. Let's investigate if we can detect type by value and support more integers caps by default

**Comment by DimaGrinevich** [comment]
Tested with dev esg;
Tested cases:
№1
    WebDriver driver;
    @BeforeTest
    public void launchDriver() {
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability("version", "91.0");
        capabilities.setCapability("idleTimeout", 72);
        driver = getDriver("default", capabilities);
    }
    
    @Test(priority = 1)
    public void testModelSpecs() throws InterruptedException {
         LOGGER.info("waiting");
        Thread.sleep(70 * 1000);
        LOGGER.info("stopped waiting");
        HomePage homePage = new HomePage(driver);
        homePage.open();
        Assert.assertTrue(homePage.isPageOpened(), "Home page is not opened")
        homePage = new HomePage(driver);
        BrandModelsPage productsPage = homePage.selectBrand("Samsung");
        ModelInfoPage productInfoPage = productsPage.selectModel("Galaxy A52 5G");
        SoftAssert softAssert = new SoftAssert();
        softAssert.assertEquals(productInfoPage.readDisplay(), "6.5\"", "Invalid display info!");
        softAssert.assertEquals(productInfoPage.readCamera(), "64MP", "Invalid camera info!");
        softAssert.assertEquals(productInfoPage.readRam(), "6/8GB RAM", "Invalid ram info!");
        softAssert.assertEquals(productInfoPage.readBattery(), "4500mAh", "Invalid battery info!");
        softAssert.assertAll();
    }


    @Test(priority = 2)
    public void testCompareModels() throws InterruptedException {
        LOGGER.info("waiting");
        pause(145);
        LOGGER.info("stopped waiting");
        HomePage homePage = new HomePage(driver);
        homePage.open();
        Assert.assertTrue(homePage.isPageOpened(), "Home page is not opened");
        FooterMenu footerMenu = homePage.getFooterMenu();
        Assert.assertTrue(footerMenu.isUIObjectPresent(2), "Footer menu wasn't found!");
        CompareModelsPage comparePage = footerMenu.openComparePage();
        List<ModelSpecs> specs = comparePage.compareModels("Samsung Galaxy J3", "Samsung Galaxy J5", "Samsung Galaxy J7 Pro");
        SoftAssert softAssert = new SoftAssert();
        softAssert.assertEquals(specs.get(0).readSpec(SpecType.ANNOUNCED), "2016, March 31");
        softAssert.assertEquals(specs.get(1).readSpec(SpecType.ANNOUNCED), "2015, June 19");
        softAssert.assertEquals(specs.get(2).readSpec(SpecType.ANNOUNCED), "2017, June");
        softAssert.assertAll();
    }
    
№2
    config.properties:
    idle_timeout=72
    
    test class:
    WebDriver driver;
    @BeforeTest
    public void launchDriver() {
        driver = getDriver();
    }
    
    @Test(priority = 1)
    public void testModelSpecs() throws InterruptedException {
         LOGGER.info("waiting");
        Thread.sleep(70 * 1000);
        LOGGER.info("stopped waiting");
        HomePage homePage = new HomePage(driver);
        homePage.open();
        Assert.assertTrue(homePage.isPageOpened(), "Home page is not opened")
        homePage = new HomePage(driver);
        BrandModelsPage productsPage = homePage.selectBrand("Samsung");
        ModelInfoPage productInfoPage = productsPage.selectModel("Galaxy A52 5G");
        SoftAssert softAssert = new SoftAssert();
        softAssert.assertEquals(productInfoPage.readDisplay(), "6.5\"", "Invalid display info!");
        softAssert.assertEquals(productInfoPage.readCamera(), "64MP", "Invalid camera info!");
        softAssert.assertEquals(productInfoPage.readRam(), "6/8GB RAM", "Invalid ram info!");
        softAssert.assertEquals(productInfoPage.readBattery(), "4500mAh", "Invalid battery info!");
        softAssert.assertAll();
    }


    @Test(priority = 2)
    public void testCompareModels() throws InterruptedException {
        LOGGER.info("waiting");
        pause(145);
        LOGGER.info("stopped waiting");
        HomePage homePage = new HomePage(driver);
        homePage.open();
        Assert.assertTrue(homePage.isPageOpened(), "Home page is not opened");
        FooterMenu footerMenu = homePage.getFooterMenu();
        Assert.assertTrue(footerMenu.isUIObjectPresent(2), "Footer menu wasn't found!");
        CompareModelsPage comparePage = footerMenu.openComparePage();
        List<ModelSpecs> specs = comparePage.compareModels("Samsung Galaxy J3", "Samsung Galaxy J5", "Samsung Galaxy J7 Pro");
        SoftAssert softAssert = new SoftAssert();
        softAssert.assertEquals(specs.get(0).readSpec(SpecType.ANNOUNCED), "2016, March 31");
        softAssert.assertEquals(specs.get(1).readSpec(SpecType.ANNOUNCED), "2015, June 19");
        softAssert.assertEquals(specs.get(2).readSpec(SpecType.ANNOUNCED), "2017, June");
        softAssert.assertAll();
    }
    
№3
    config.properties:
    idle_timeout=72
    
    test class:
    WebDriver driver;
    @BeforeTest
    public void launchDriver() {
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability("version", "91.0");
        capabilities.setCapability("idleTimeout", 150);
        driver = getDriver("default", capabilities);
    }
    
    @Test()
    public void testModelSpecs() throws InterruptedException {
         LOGGER.info("waiting");
        Thread.sleep(148 * 1000);
        LOGGER.info("stopped waiting");
        HomePage homePage = new HomePage(driver);
        homePage.open();
        Assert.assertTrue(homePage.isPageOpened(), "Home page is not opened");
        homePage = new HomePage(driver);
        BrandModelsPage productsPage = homePage.selectBrand("Samsung");
        ModelInfoPage productInfoPage = productsPage.selectModel("Galaxy A52 5G");
        SoftAssert softAssert = new SoftAssert();
        softAssert.assertEquals(productInfoPage.readDisplay(), "6.5\"", "Invalid display info!");
        softAssert.assertEquals(productInfoPage.readCamera(), "64MP", "Invalid camera info!");
        softAssert.assertEquals(productInfoPage.readRam(), "6/8GB RAM", "Invalid ram info!");
        softAssert.assertEquals(productInfoPage.readBattery(), "4500mAh", "Invalid battery info!");
        softAssert.assertAll();
    }
    
№4
    config.properties:
    idle_timeout=150
            
    test class:
    WebDriver driver;
    @BeforeTest
    public void launchDriver() {
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability("version", "91.0");
        capabilities.setCapability("idleTimeout", 72);
        driver = getDriver("default", capabilities);
    }
    
    @Test()
    public void testModelSpecs() throws InterruptedException {
         LOGGER.info("waiting");
        Thread.sleep(147 * 1000);
        LOGGER.info("stopped waiting");
        HomePage homePage = new HomePage(driver);
        homePage.open();
        Assert.assertTrue(homePage.isPageOpened(), "Home page is not opened");
        homePage = new HomePage(driver);
        BrandModelsPage productsPage = homePage.selectBrand("Samsung");
        ModelInfoPage productInfoPage = productsPage.selectModel("Galaxy A52 5G");
        SoftAssert softAssert = new SoftAssert();
        softAssert.assertEquals(productInfoPage.readDisplay(), "6.5\"", "Invalid display info!");
        softAssert.assertEquals(productInfoPage.readCamera(), "64MP", "Invalid camera info!");
        softAssert.assertEquals(productInfoPage.readRam(), "6/8GB RAM", "Invalid ram info!");
        softAssert.assertEquals(productInfoPage.readBattery(), "4500mAh", "Invalid battery info!");
        softAssert.assertAll();
    }

**Comment by vdelendik** [comment]
reorganized in better way where all capabilities are parsed... also submitted one more core improvement: #1463
