### ISSUE TITLE
404 error after redirection to Zebrunner landing page

### ISSUE THREAD

**Issue by dhreben** [zebrunner/carina#1436]
**Test scenario:**

1. Open https://www.carina-core.io/
2. Click 'Learn more' Zebrunner

**Actual result:**  404 error after redirection to Zebrunner landing page

 <img width="603" alt="Screenshot 2021-08-11 at 14 01 28" src="https://user-images.githubusercontent.com/50950954/129018137-62d2a0e0-fba4-494a-b8a2-d17d94f7edb2.png">

**Comment by DimaGrinevich** [comment]
https://github.com/zebrunner/zebrunner/commit/1f3e6458af1a78bbaa823a92700a34cc2fd7ddb5
https://github.com/zebrunner/zebrunner/commit/7a3a035c4654bfa4b9961e01b6712ff43cecedf6

**Comment by dhreben** [comment]
The same issue on  https://www.qps-infra.io after click "Read more" on Zafira

**Comment by okamara** [comment]
Verified, fixed.
