### ISSUE TITLE
Upgrade to the latest version of Apache Struts

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/carina#1442]
Vulnerable software installed: Apache Struts 1.3.8
(/home/zebrunner/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar)
Solution:- Upgrade to the latest version of Apache Struts

**Comment by vdelendik** [comment]
closing as not a bug because none of zebrunner automation project use this dependency. it might appear on test project level
