### ISSUE TITLE
L10N : locale variable is declared as a static, unable to make changes via R.CONFIG.put("locale", localeStr);

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/carina#1447]
L10N : locale variable is declared as a static, unable to make changes via R.CONFIG.put("locale", "es_ES");

It should be nonstatic so user can change the locale during runtime.

**Comment by DimaGrinevich** [comment]
Could be tested with **7.2.10-localeRuntime-SNAPSHOT**
To change locale in runtime use `L10N.setLocale("es_ES");`
