### ISSUE TITLE
hide `WARN! Value not resolved by key: azure_container_name`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1451]
refactor configuration parameter usage to avoid below exception:
WARN! Value not resolved by key: azure_container_name

Also remove from loggers default `azure_blob_url=https://NULL.blob.core.windows.net` param if nothing is updated

**Comment by vdelendik** [comment]
done. to test run api-demo-test using `7.2.10-SNAPSHOT` carina
->no more by default among console logs:
```
WARN! Value not resolved by key: azure_container_name
...
azure_blob_url=https://NULL.blob.core.windows.net
```

**Comment by DimaGrinevich** [comment]
still can be seen at logs
`azure_blob_url=https://NULL.blob.core.windows.net`
