### ISSUE TITLE
Disable all snapshot builds before release

### ISSUE THREAD

**Issue by DimaGrinevich** [zebrunner/carina#1456]
May occur such warnings
`[WARNING] Could not transfer metadata io.cucumber:messages/maven-metadata.xml from/to zebrunner_snapshots (https://nexus.zebrunner.dev/repository/ce-snapshots/): Transfer failed for https://nexus.zebrunner.dev/repository/ce-snapshots/io/cucumber/messages/maven-metadata.xml`

**Comment by vdelendik** [comment]
done. during the testing double check that there is no warnings anymore
