### ISSUE TITLE
add documentation explanation for `ignore_ssl` property

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1480]
https://zebrunner.github.io/carina/configuration/

**Comment by vdelendik** [comment]
done. info should be present on doc web-site asap.

**Comment by okamara** [comment]
Verified on https://zebrunner.github.io/carina/configuration/
<img width="715" alt="Снимок экрана 2021-11-10 в 17 09 30" src="https://user-images.githubusercontent.com/32964663/141128274-17befc6a-a74b-4326-bf2c-44e995ec22df.png">
