### ISSUE TITLE
Appium 2.0 features support though out framework

### ISSUE THREAD

**Issue by tvtester** [zebrunner/carina#1483]
**Describe the solution you'd like**

**Additional context**
Add any other context about the feature request here.

**Comment by akamarouski** [comment]
closed by #1810

**Comment by akamarouski** [comment]
Test on the following configuration:
carina: 8.0.0-SNAPSHOT
carina-demo branch: carina-8.x

**Comment by okamara** [comment]
Verified, fixed.
