### ISSUE TITLE
let's generate Advance->Mobile article with extra information

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1485]
1. how to run one test on android and ios in parallel?
2. how to run on tvOS, AndroidTV
3. something else? (need review telegram channel to collect most of the popular questions)

**Comment by okamara** [comment]
doc updates is not present here https://zebrunner.github.io/carina/automation/mobile/

**Comment by akamarouski** [comment]
doc updated: https://zebrunner.github.io/carina/advanced/mobile/

**Comment by okamara** [comment]
verified, need update link here For more info visit [tvOS appium support](https://appium.io/docs/en/writing-running-appium/ios/ios-tvos/).

**Comment by okamara** [comment]
Verified, fixed.
