### ISSUE TITLE
Extra report folders creation

### ISSUE THREAD

**Issue by DimaGrinevich** [zebrunner/carina#1488]
Carina creates extra folders during run, because test report folder known only in one thread (private static final ThreadLocal<File> testDirectory = new ThreadLocal<File>(); in ReportContext) when driver do some actions in new thread, but connected with the same test. For example openURL in DriverHelper. There new thread created with Future<?> future = Executors.newSingleThreadExecutor().submit(new Callable<Void>() {}. Thats why every log in new thread is going to new report. and even if we delete all logs from call method, DriverListener also uses new thread and logs everything into new folder (screenshot from DriverListener goes to new folder too).

**Comment by vdelendik** [comment]
testing should be done using `7.2.14-SNAPHOT` core version

**Comment by okamara** [comment]
Verified by customer, fixed.
