### ISSUE TITLE
bump up to the selenium 4.0.0

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1490]
changes:
https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG

https://www.selenium.dev/blog/2021/announcing-selenium-4/

upgrade recommendations:
https://www.selenium.dev/documentation/getting_started/how_to_upgrade_to_selenium_4/

authentication feature:
https://www.selenium.dev/blog/2021/a-tour-of-4-authentication/

**Comment by akamarouski** [comment]
closed by #1664
