### ISSUE TITLE
remove deprecated testrai related artifacts in SpecialKeywords

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1491]
@Deprecated
    public static final String TESTRAIL_SUITE_ID_OLD = "TestRailSuiteId";
    @Deprecated
    public static final String TESTRAIL_PROJECT_ID_OLD = "TestRailProjectId";
    public static final String TESTRAIL_SUITE_ID = "com.zebrunner.app/tcm.testrail.suite-id";
    @Deprecated
    public static final String TESTRAIL_PROJECT_ID = "com.zebrunner.app/tcm.testrail.project-id";
    @Deprecated
    public static final String TESTRAIL_TESTCASE_UUID = "com.zebrunner.app/tcm.testrail.testcase-id";

**Comment by vdelendik** [comment]
testing should include running api and web job on `7.3.15-SNAPSHOT` carina on Pro and CE versions. everything should be executed and tracked.

**Comment by okamara** [comment]
Verified on develop branch on CE, fixed.
