### ISSUE TITLE
let's make `Unable to capture screenshot during ...sec!` as WARN

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1492]
1. change log level for such message from ERROR to WARN:
`Unable to capture screenshot during 6sec!`
2. add space between `number` and `sec`

**Comment by vdelendik** [comment]
@okamara please retest again and provide prove as screenshot to me before reopening again :)
you might use 7.2.14 core release for that

**Comment by okamara** [comment]
Verified on 7.3.15, fixed.
<img width="875" alt="Снимок экрана 2021-12-06 в 19 27 09" src="https://user-images.githubusercontent.com/32964663/144884628-fd379223-c127-4b66-9224-ead6255a11a1.png">
