### ISSUE TITLE
Couldn't Create New Session after adding chrome experimental options in _config.properties file

### ISSUE THREAD

**Issue by goofyd** [zebrunner/carina#1495]
Couldn't Create New Session after adding the below chrome experimental options in _config.properties file

`chrome_args=--disable-notifications,--use-fake-device-for-media-stream,--use-fake-ui-for-media-stream
chrome_experimental_opts=profile.default_content_setting_values.media_stream_mic=1,profile.default_content_setting_values.media_stream_camera=1,profile.default_content_setting_values.geolocation=1,profile.default_content_setting_values.notifications=1
`

`{
  "value": {
    "stacktrace": "org.openqa.selenium.SessionNotCreatedException: Unable to create session from {\n  \"desiredCapabilities\": {\n    \"chrome.switches\": [\n      \"--start-maximized\",\n      \"--ignore-ssl-errors\"\n    ],\n    \"acceptSslCerts\": true,\n    \"goog:chromeOptions\": {\n      \"args\": [\n        \"test-type\",\n        \"--disable-notifications\",\n        \"--use-fake-device-for-media-stream\",\n        \"--use-fake-ui-for-media-stream\"\n      ],\n      \"extensions\": [\n      ],\n      \"prefs\": {\n        \"download.prompt_for_download\": false,\n        \"plugins.always_open_pdf_externally\": true,\n        \"download.default_directory\": \"D:\\\\repos\\\\seleniumwebautomation\\\\.\\\\reports\\\\Screenshots\\\\1635429041406\\\\artifacts\"\n      },\n      \"profile.default_content_setting_values.geolocation\": \"1\",\n      \"profile.default_content_setting_values.media_stream_camera\": \"1\",\n      \"profile.default_content_setting_values.media_stream_mic\": \"1\",\n      \"profile.default_content_setting_values.notifications\": \"1\"\n    },\n    \"acceptInsecureCerts\": true,\n    \"name\": \"default\",\n    \"browserName\": \"chrome\",\n    \"takesScreenshot\": false,\n    \"carinaTestRunId\": \"50e8420f-419e-49a2-9cb7-121ba0c30f4a\",\n    \"version\": \"\"\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"acceptInsecureCerts\": true,\n        \"browserName\": \"chrome\",\n        \"goog:chromeOptions\": {\n          \"args\": [\n            \"test-type\",\n            \"--disable-notifications\",\n            \"--use-fake-device-for-media-stream\",\n            \"--use-fake-ui-for-media-stream\"\n          ],\n          \"extensions\": [\n          ],\n          \"prefs\": {\n            \"download.prompt_for_download\": false,\n            \"plugins.always_open_pdf_externally\": true,\n            \"download.default_directory\": \"D:\\\\repos\\\\seleniumwebautomation\\\\.\\\\reports\\\\Screenshots\\\\1635429041406\\\\artifacts\"\n          },\n          \"profile.default_content_setting_values.geolocation\": \"1\",\n          \"profile.default_content_setting_values.media_stream_camera\": \"1\",\n          \"profile.default_content_setting_values.media_stream_mic\": \"1\",\n          \"profile.default_content_setting_values.notifications\": \"1\"\n        }\n      }\n    ]\n  }\n}\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'DESKTOP-6KDP54L', ip: '192.168.0.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'\nDriver info: driver.version: unknown\r\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$4(NewSessionPipeline.java:76)\r\n\tat java.util.Optional.orElseThrow(Unknown Source)\r\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$5(NewSessionPipeline.java:75)\r\n\tat java.util.Optional.orElseGet(Unknown Source)\r\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:73)\r\n\tat org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)\r\n\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n",
    "stackTrace": [
      {
        "fileName": "NewSessionPipeline.java",
        "methodName": "lambda$null$4",
        "className": "org.openqa.selenium.remote.server.NewSessionPipeline",
        "lineNumber": 76
      },
      {
        "fileName": null,
        "methodName": "orElseThrow",
        "className": "java.util.Optional",
        "lineNumber": -1
      },
      {
        "fileName": "NewSessionPipeline.java",
        "methodName": "lambda$createNewSession$5",
        "className": "org.openqa.selenium.remote.server.NewSessionPipeline",
        "lineNumber": 75
      },
      {
        "fileName": null,
        "methodName": "orElseGet",
        "className": "java.util.Optional",
        "lineNumber": -1
      },
      {
        "fileName": "NewSessionPipeline.java",
        "methodName": "createNewSession",
        "className": "org.openqa.selenium.remote.server.NewSessionPipeline",
        "lineNumber": 73
      },
      {
        "fileName": "BeginSession.java",
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.server.commandhandler.BeginSession",
        "lineNumber": 65
      },
      {
        "fileName": "WebDriverServlet.java",
        "methodName": "lambda$handle$0",
        "className": "org.openqa.selenium.remote.server.WebDriverServlet",
        "lineNumber": 235
      },
      {
        "fileName": null,
        "methodName": "call",
        "className": "java.util.concurrent.Executors$RunnableAdapter",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "run",
        "className": "java.util.concurrent.FutureTask",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "runWorker",
        "className": "java.util.concurrent.ThreadPoolExecutor",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "run",
        "className": "java.util.concurrent.ThreadPoolExecutor$Worker",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "run",
        "className": "java.lang.Thread",
        "lineNumber": -1
      }
    ],
    "message": "Unable to create session from {\n  \"desiredCapabilities\": {\n    \"chrome.switches\": [\n      \"--start-maximized\",\n      \"--ignore-ssl-errors\"\n    ],\n    \"acceptSslCerts\": true,\n    \"goog:chromeOptions\": {\n      \"args\": [\n        \"test-type\",\n        \"--disable-notifications\",\n        \"--use-fake-device-for-media-stream\",\n        \"--use-fake-ui-for-media-stream\"\n      ],\n      \"extensions\": [\n      ],\n      \"prefs\": {\n        \"download.prompt_for_download\": false,\n        \"plugins.always_open_pdf_externally\": true,\n        \"download.default_directory\": \"D:\\\\repos\\\\seleniumwebautomation\\\\.\\\\reports\\\\Screenshots\\\\1635429041406\\\\artifacts\"\n      },\n      \"profile.default_content_setting_values.geolocation\": \"1\",\n      \"profile.default_content_setting_values.media_stream_camera\": \"1\",\n      \"profile.default_content_setting_values.media_stream_mic\": \"1\",\n      \"profile.default_content_setting_values.notifications\": \"1\"\n    },\n    \"acceptInsecureCerts\": true,\n    \"name\": \"default\",\n    \"browserName\": \"chrome\",\n    \"takesScreenshot\": false,\n    \"carinaTestRunId\": \"50e8420f-419e-49a2-9cb7-121ba0c30f4a\",\n    \"version\": \"\"\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"acceptInsecureCerts\": true,\n        \"browserName\": \"chrome\",\n        \"goog:chromeOptions\": {\n          \"args\": [\n            \"test-type\",\n            \"--disable-notifications\",\n            \"--use-fake-device-for-media-stream\",\n            \"--use-fake-ui-for-media-stream\"\n          ],\n          \"extensions\": [\n          ],\n          \"prefs\": {\n            \"download.prompt_for_download\": false,\n            \"plugins.always_open_pdf_externally\": true,\n            \"download.default_directory\": \"D:\\\\repos\\\\seleniumwebautomation\\\\.\\\\reports\\\\Screenshots\\\\1635429041406\\\\artifacts\"\n          },\n          \"profile.default_content_setting_values.geolocation\": \"1\",\n          \"profile.default_content_setting_values.media_stream_camera\": \"1\",\n          \"profile.default_content_setting_values.media_stream_mic\": \"1\",\n          \"profile.default_content_setting_values.notifications\": \"1\"\n        }\n      }\n    ]\n  }\n}\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'DESKTOP-6KDP54L', ip: '192.168.0.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'\nDriver info: driver.version: unknown",
    "error": "session not created"
  },
  "status": 33
}`

**Comment by vdelendik** [comment]
@goofyd, reanalyzed your PR automatically after restoring CI/CD analysis in new zebrunner organization.
So wanna to mention that you can now get SNAPSHOT carina-core build for every your PR, for example:
![image](https://user-images.githubusercontent.com/4551455/140757467-f8f1773b-484d-4279-b1d0-6968f9ecf35a.png)

also after merging to master, we do force rebuild to the upcoming release tag, i.e. `7.2.13-SNAPSHOT` as well. This version will have all consolidated 7.2.13 changes in master...

Please, test and let us know if everything is ok now.

**Comment by Eldarian** [comment]
Session has been successfully created with the following options:
 `chrome_args=--disable-notifications,--use-fake-device-for-media-stream,--use-fake-ui-for-media-stream chrome_experimental_opts=profile.default_content_setting_values.media_stream_mic=1,profile.default_content_setting_values.media_stream_camera=1,profile.default_content_setting_values.geolocation=1,profile.default_content_setting_values.notifications=1`

**Comment by vdelendik** [comment]
moved to done based on comment above
