### ISSUE TITLE
update CONTRIBUTING.md adding details about new CI/CD pipelines

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1511]
https://github.com/zebrunner/carina/blob/master/CONTRIBUTING.md

1. add information about required quality gates based on sonar analysis
2. describe in details with screenshots information about snapshots build generation process for PR's and merges
3. better to fix in advance [#1453] to have new snapshot repos

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/carina/blob/master/CONTRIBUTING.md
@avabishchevich, please check wording

**Comment by okamara** [comment]
wording was verified by @avabishchevich
