### ISSUE TITLE
investigate possibility to completely remove elements caching

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1523]
This time selenium and appium much more stable and it has sense again to enable dynamic element search everytime without caching.
Moreover all kind of verifications moved into the flueat waiters which significantly decreased number of direct selenium/appium calls

ExtendedElementLocator class has pretty fast findElement and findElements overridden so caching might be a problem now especially for such frameworks as google web toolkit, react applications etc

**Comment by vdelendik** [comment]
implementation is here: https://github.com/zebrunner/carina/pull/1535

**Comment by vdelendik** [comment]
done in scope of huge refactoring. for testing we have to run regular full_regression cron in carina-demo using `7.3.15-SNAPSHOT` carina

**Comment by okamara** [comment]
Verified on zebrunner form develop branch, branch=7.3.15
