### ISSUE TITLE
be able to disable cache lookup for extended web elements via single property

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1524]
related ticket is https://github.com/zebrunner/carina/issues/1523

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/carina/pull/1522

it would be great during the testing run our regular web/android/ios tests as it using `7.2.13-SNAPSHOT` carina.
After that provide via overrideFields `disable_cache_lookup=true` and run again the same tests.

1. results for pass/failure should be the same
2. pay attention to the executed time, ideally it should be almost the same but let @vdelendik know exactnumbers

**Comment by okamara** [comment]
Time difference for Web-demo test job 13 sec
<img width="1098" alt="Снимок экрана 2021-12-08 в 00 26 23" src="https://user-images.githubusercontent.com/32964663/145108567-28f30cdf-dac7-4d1a-83db-1ef424b645f8.png">
