### ISSUE TITLE
introduce new `crypto_key_value` property for CONFIG dataset

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1525]
as we can use env variables we could try to switch onto the new `crypto_key_value` approach as part of regular CONFIG context.

1. declare new `crypto_key_value=NULL`
2. if it is non empty it should have priority in comparison with `crypto_key_path`
3. crypto_key_path should be used only if crypto_key_value is not available

Such approach might organize movement to new security approach on CI with better flexibilities

**Comment by vdelendik** [comment]
ticket might be verified using `7.4.22-SNPASHOT`

**Comment by vdelendik** [comment]
reopened to deliver in better way using separated maven or even gradle project

**Comment by vdelendik** [comment]
crypto-key project should be released soon by me (already with `com.zebrunner` packages)

**Comment by akamarouski** [comment]
For QA:
carina version: 8.0.1-SNAPSHOT

**Comment by okamara** [comment]
verified by @akamarouski
