### ISSUE TITLE
review default config params value making them hidden by default in the log

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1537]
That's latest log messages top from carina-demo project using 7.2.14 core
Let's review and make most of them NULL, i.e. hidden by default and init by default values only when needed in Configuration.java
Make sure to inspect unit tests after that.

Goal to keep only updated and the most important in the logs

```
url=https://www.gsmarena.com
env=DEMO
max_driver_count=3
proxy_protocols=http,https,ftp
browsermob_port=0
auto_screenshot=true
explicit_timeout=20
retry_interval=5
project_report_directory=./reports
max_screen_history=10
big_screen_width=-1
big_screen_height=-1
init_retry_count=0
init_retry_interval=1
retry_count=0
locale=en_US
thread_count=-1
data_provider_thread_count=-1
core_log_level=INFO
core_log_packages=com.qaprosoft.carina.core
log_all_json=true
date_format=HH:mm:ss yyyy-MM-dd
time_format=HH:mm:ss
test_naming_pattern={method_name}
element_loading_strategy=BY_PRESENCE_OR_VISIBILITY
page_opening_strategy=BY_URL_AND_ELEMENT
localization_encoding=UTF-8
localization_testing=false
default_device_timezone=GMT
default_device_time_format=24
default_device_language=en_US
selenium_url=
```

**Comment by vdelendik** [comment]
the easiest way might be:
1. provide NULL values for any config.properties parameters
2. create new default.properties file with default values. it might be injected on R init phase. During initialization from this step nothing should be written in log.
3. when property is inited/updated after `default.properties` init we can put appropriate message to log.

**Comment by okamara** [comment]
Verified, fixed.
