### ISSUE TITLE
combine doClick and doTap

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1540]
as for now there is no difference in click method so let's keep the only action as of now `doClick`

**Comment by vdelendik** [comment]
done. during the testing just execute web and android jobs. all should be executed as earlier

**Comment by okamara** [comment]
Verified on develop branch for web demo test only, carina-core_version=7.3.15-SNAPSHOT , branch =7.3.15. Need run API demo test job after bug fix.
