### ISSUE TITLE
remove timer and iPerformance operation from carina

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1541]
carina is execution framework and not a reporting so we have to remove deprecated and unused timer and IPerformanceOperation

**Comment by vdelendik** [comment]
done. for testing it is enough to run any api test using `7.3.15-SNAPSHOT` carina. 
to simplify process I added inside carina-demo project branch with this carina: `7.3.15`

**Comment by okamara** [comment]
Verified on web demo test only, fixed.
