### ISSUE TITLE
remove deprecated SpecialKeywords.QTEST_PROJECT_ID_OLD

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1542]
subj

**Comment by vdelendik** [comment]
done. for testing it is enough to execute any api test from carina-demo on branch `7.3.15` where valid snapshot carina is used

**Comment by okamara** [comment]
Verified on develop branch for web demo test only, carina-core_version=7.3.15-SNAPSHOT , branch =7.3.15
