### ISSUE TITLE
Webdriver can't start from android emulator

### ISSUE THREAD

**Issue by Trukhanovich** [zebrunner/carina#1545]
[2021-12-03 05:26:44] [Configuration.java] [1] [WARN] selenium_host configuration parameter is deprecated. Please, start using SELENIUM_URL instead!
[2021-12-03 05:26:44] [CarinaListener.java] [1] [INFO] 
============= Test configuration =============
url=https://stage. projectname.biz
env=STAG
browser=chrome
selenium_host=http://localhost:4723/wd/hub
max_driver_count=3
chrome_experimental_opts=w3c=false
chrome_closure=true
proxy_protocols=http,https,ftp
browsermob_port=0
auto_screenshot=false
explicit_timeout=20
auto_download=false
retry_interval=5
project_report_directory=./reports/qa
max_screen_history=10
big_screen_width=-1
big_screen_height=-1
init_retry_count=0
init_retry_interval=1
retry_count=0
locale=en_US
thread_count=1
data_provider_thread_count=-1
core_log_level=INFO
core_log_packages=com.qaprosoft.carina.core
log_all_json=false
date_format=HH:mm:ss yyyy-MM-dd
time_format=HH:mm:ss
test_naming_pattern={method_name}
element_loading_strategy=BY_PRESENCE_OR_VISIBILITY
page_opening_strategy=BY_URL_AND_ELEMENT
localization_encoding=utf-8
localization_testing=false
default_device_timezone=GMT
default_device_time_format=24
default_device_language=en_US
selenium_url=http://localhost:4723/wd/hub

------------- Driver capabilities -----------
capabilities.STF_ENABLED=false
capabilities.udid=emulator-5554
capabilities.deviceName=Galaxy_S8_Redirect
capabilities.platform=ANDROID
capabilities.browserName=Chrome
capabilities.platformVersion=8.0
capabilities.automationName=UiAutomator2
capabilities.newCommandTimeout=180
capabilities.platformName=Android
capabilities.appWaitDuration=270000
================================================

[2021-12-03 05:26:44] [TestRunRegistrar.java] [1] [WARN] Reporting disabled: using no op test run registrar
[2021-12-03 05:26:45] [Reflections.java] [1] [INFO] Reflections took 995 ms to scan 6 urls, producing 2120 keys and 11403 values 
[2021-12-03 05:26:45] [FilterTestsListener.java] [1] [INFO] There are no any rules and limitations
[2021-12-03 05:26:45] [CarinaListener.java] [1] [INFO] Set data-provider-thread-count=1
[2021-12-03 05:26:45] [CarinaListener.java] [1] [INFO] CARINA_CORE_VERSION: 7.2.14
[2021-12-03 05:26:45] [TestRunRegistrar.java] [1] [WARN] Reporting disabled: using no op test run registrar
[2021-12-03 05:26:45] [TestRunRegistrar.java] [1] [WARN] Reporting disabled: using no op test run registrar
[2021-12-03 05:26:45] [IMessager.java] [1] [INFO] TEST [projectname-automation - verifyRedesignedSummaryTableTest] STARTED at [17:26:45 2021-12-03]
[2021-12-03 05:26:46] [Configuration.java] [1] [WARN] selenium_host configuration parameter is deprecated. Please, start using SELENIUM_URL instead!
[2021-12-03 05:26:52] [IDriverPool.java] [1] [ERROR] Driver initialization 'default' FAILED! Retry 1 of 1 time - org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: chromeOptions
from invalid argument: unrecognized chrome option: prefs
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Mac OS X 10.16.0 x86_64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'atrukhanovich', ip: 'fe80:0:0:0:1002:b358:8c44:4fa3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.11'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: chromeOptions
from invalid argument: unrecognized chrome option: prefs
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Mac OS X 10.16.0 x86_64)
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
[2021-12-03 05:26:52] [IMessager.java] [1] [ERROR] TEST [projectname-automation - verifyRedesignedSummaryTableTest] FAILED at [17:26:52 2021-12-03] - org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: chromeOptions
from invalid argument: unrecognized chrome option: prefs
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Mac OS X 10.16.0 x86_64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'atrukhanovich', ip: 'fe80:0:0:0:1002:b358:8c44:4fa3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.11'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: chromeOptions
from invalid argument: unrecognized chrome option: prefs
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Mac OS X 10.16.0 x86_64)
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:182)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
org.openqa.selenium.remote.RemoteWebDriver.startSession$original$0dimmhB5(RemoteWebDriver.java:213)
org.openqa.selenium.remote.RemoteWebDriver.startSession$original$0dimmhB5$accessor$AnRkUZ2u(RemoteWebDriver.java)
org.openqa.selenium.remote.RemoteWebDriver$auxiliary$8pitJoel.run(Unknown Source)
com.zebrunner.agent.core.webdriver.StartSessionInterceptor.onSessionStart(StartSessionInterceptor.java:35)
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java)
io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:338)
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:86)
com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.MobileFactory.create(MobileFactory.java:89)
com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:78)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.createDriver(IDriverPool.java:387)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:129)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:85)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:72)
com. projectname.qa.webtests.AbstractProjectnameTest.getDriver(AbstractProjectnameTest.java:121)
com.projectname.qa.mobileweb.credit.roundups.CreditCardsRoundupsTest.verifyRedesignedSummaryTableTest(CreditCardsRoundupsTest.java:591)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
org.testng.TestRunner.privateRun(TestRunner.java:794)
org.testng.TestRunner.run(TestRunner.java:596)
org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
org.testng.SuiteRunner.run(SuiteRunner.java:276)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
org.testng.TestNG.runSuites(TestNG.java:1063)
org.testng.TestNG.run(TestNG.java:1031)
com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

**Comment by vdelendik** [comment]
fix merged: https://github.com/zebrunner/carina/pull/1557
Changes might be tested in `7.3.15-SNAPSHOT` core

**Comment by vdelendik** [comment]
testing confirmed fix
