### ISSUE TITLE
docs: sync contribution article with latest repo updates

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1547]
actual info:
https://github.com/zebrunner/carina/blob/master/CONTRIBUTING.md

out-of-dated:
https://zebrunner.github.io/carina/contribution/

**Comment by vdelendik** [comment]
done. 2nd page should have almost the same content. make sure to verify all links inside!
https://zebrunner.github.io/carina/contribution/

**Comment by okamara** [comment]
Verified, fixed.
