### ISSUE TITLE
Incorrect total threads count calculations in terms of multiple data-provider-thread-count value

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/carina#1555]
**Description**
Starting from Carina 7.2.12, exactly from migration to TestNG 7.4.0 https://github.com/zebrunner/carina/pull/1481 it looks like total threads count value has started to be calculated by the following formula:

`data-provider-thread-count*thread-count (smth like product)`

**While expected value should be** 

`data-provider-thread-count+thread-count (sum of 2 values)`

**Tested platforms**
- Desktop
- iOS
- Android

**Tested carina versions:**
- 7.2.12
- 7.2.14

**Comment by vdelendik** [comment]
@rkatuzhanets, closing as it it working as designed in TestNG.
Every independent thread might reuse their own data-provider multi-threading so we have to be very careful using these approaches both together.
