### ISSUE TITLE
Carina-SOAP 

### ISSUE THREAD

**Issue by nirajk1083** [zebrunner/carina#1565]
Need migration request on JAVA 11 from Java 8

https://github.com/zebrunner/carina-soap.git

**Comment by vdelendik** [comment]
done. carina-soap project updated.
to test please register/scan in zebrunner CE jenkins https://github.com/zebrunner/carina-soap.git and run single SOAP-Demo-Test job 
-> one test should pass, appropriate data and logs registered in zebrunner reporting

**Comment by okamara** [comment]
Verified on develop branch, done.
<img width="1376" alt="Снимок экрана 2022-01-17 в 14 31 07" src="https://user-images.githubusercontent.com/32964663/149762231-3fe4e863-ae0b-4053-822c-03d3d0d63adf.png">
