### ISSUE TITLE
migrate to modern logger implementation

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1566]
perform one more attempt to jump onto any modern logger (log4j2x or logback).
Seems like the only blocker is ThreadLogAppender as of now

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/carina/pull/1582
also adjusted carina-demo: https://github.com/zebrunner/carina-demo/pull/207
and carina archetype accordingly...

to test run regular regressions from carina-demo (branch: master) and inspect test logs carefully...

**Comment by okamara** [comment]
Created a separate issue https://github.com/zebrunner/reporting/issues/2338
