### ISSUE TITLE
404 error after redirection to User Guide Zebrunner CE 

### ISSUE THREAD

**Issue by dhreben** [zebrunner/carina#1570]
**Steps:**
1. Open https://zebrunner.github.io/carina/zebrIntegration/
2. Click User Guide Link 

**Actual result:**  404 error after redirection to Zebrunner CE User Guide
**Expected result:**  Link redirection to https://zebrunner.github.io/community-edition/user-guide/

Please see screenshot: 

<img width="728" alt="Screenshot 2022-01-05 at 12 57 05" src="https://user-images.githubusercontent.com/50950954/148198203-754c7c6d-38bd-4ef7-955a-d4ff52834315.png">

**Comment by vdelendik** [comment]
Zebrunner integration page updated a lot including fix for the user guide link which seems to be removed:)
https://zebrunner.github.io/carina/integration/zebrunner/

**Comment by dhreben** [comment]
Verified.
