### ISSUE TITLE
remove "default" driver name capability registration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1573]
We register capabilities.name based on driver name. Let's skip this field for "default" to have regular selenium sessionId assigned.
But let's continue to substitute for non "default" use case

**Comment by vdelendik** [comment]
done. @okamara testing should be done using `7.3.15-SNAPSHOT` carina.
just execute on any env web-demo-test job. Video recording driver session should be named having long uuid instead of "default"

**Comment by okamara** [comment]
Verified, fixed.
