### ISSUE TITLE
bump up java appium client 7.5.1 -> 7.6.0

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1574]
due to the w3c caps limitation in 7.6.0 appium java client library we decided to postpone migration till 7.3.16 core release.
7.3.15 should come with 7.5.1 and enhanced driver connection refused, 7.6.0 should appear after we finish migration of mcloud and esg onto the w3s completely

**Comment by vdelendik** [comment]
#1574 branch was created with 7.6.0 java client and adjusted event firing command executor!

**Comment by okamara** [comment]
Tested on https://demo.zebrunner.org/
