### ISSUE TITLE
Incorrect quantity of free trial period: 30 instead of 14 on Zebrunner Reporting Integration page

### ISSUE THREAD

**Issue by dhreben** [zebrunner/carina#1577]
**Steps:**

1. Open https://zebrunner.github.io/carina/integration/zebrunner/
2. Scroll down the page

**Actual result:** Incorrect quantity of free trial period: 30 instead of 14 on Zebrunner Reporting Integration page

<img width="978" alt="Screenshot 2022-01-17 at 11 46 50" src="https://user-images.githubusercontent.com/50950954/149737244-bfea724f-f478-4468-91f4-a6f85ffef6d7.png">

**Comment by vdelendik** [comment]
fixed: https://zebrunner.github.io/carina/integration/zebrunner/

**Comment by okamara** [comment]
Verified, fixed.
