### ISSUE TITLE
desired capabilities annotation for tests needed

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/carina#158]
Sometimes we should execute test only on specific Android versions. For example we know that there are known automation limitations on Android versions <= 5.0.2, and some porblems on 5.1.1 but for 5.1 and 6+ everything is ok. To increase performance we can mark in annotation execution priority, or device os versions range, etc. 

For example:
@SkipAndroidVersions("<5.1", "5.1.1")
@ExecutingPreorityOfAndroidVersions("7.0","6.0.1","7.1.1","6.0","5.1.1") 
And in such case CI should try to execute this test first on first available device with os version 7.0, than if no such device - on 6.0.1 and so on. And skip all devices with os from Skip List. Postpond for availability any device from White list. 

Similar thing can be used for iOS.

**Comment by vdelendik** [comment]
also as one of the important - ability to use direct adb connection so we can later remove it from global configuration and provide only for tests/driver where it is really needed

**Comment by vdelendik** [comment]
closing as won't fix (out-of-dated)
