### ISSUE TITLE
Unable to initialize the driver with browser mob proxy capabilities

### ISSUE THREAD

**Issue by tvtester** [zebrunner/carina#1586]
**Describe the bug**
BrowserMob proxy capabilities is defined in the config file as per doc: https://zebrunner.github.io/carina/advanced/proxy/
It is failing in the below code of last if condition where proxy.start(proxyPort); is defined. This issue is happening with latest v7.3.15
It is working fine on previous v7.2.14

```
public static synchronized BrowserMobProxy startProxy(int proxyPort) {
        if (!Configuration.getBoolean(Parameter.BROWSERMOB_PROXY)) {
            LOGGER.debug("Proxy is disabled.");
            return null;
        } else {
            BrowserMobProxy proxy = null;
            long threadId = Thread.currentThread().getId();
            if (proxies.containsKey(threadId)) {
                proxy = (BrowserMobProxy)proxies.get(threadId);
            }

            if (proxyPortsByThread.containsKey(threadId)) {
                proxyPort = (Integer)proxyPortsByThread.get(threadId);
            }

            if (null == proxy || proxy.getPort() != proxyPort) {
                proxy = createProxy();
                proxies.put(Thread.currentThread().getId(), proxy);
            }

            if (!proxy.isStarted()) {
                LOGGER.info("Starting BrowserMob proxy...");
                killProcessByPort(proxyPort);
                proxy.start(proxyPort);
            } else {
                LOGGER.info("BrowserMob proxy is already started on port " + proxy.getPort());
            }

            return proxy;
        }
    }
```

**Logs/Links**
2022-02-01 17:19:56 TestRunRegistrar [main-1] [WARN] Reporting disabled: using no op test run registrar
2022-02-01 17:19:56 Reflections [main-1] [INFO] Reflections took 778 ms to scan 8 urls, producing 1753 keys and 8251 values 
2022-02-01 17:19:57 FilterTestsListener [main-1] [INFO] There are no any rules and limitations
2022-02-01 17:19:57 CarinaListener [main-1] [INFO] Set thread-count=1
2022-02-01 17:19:57 CarinaListener [main-1] [INFO] Set data-provider-thread-count=1
2022-02-01 17:19:57 CarinaListener [main-1] [INFO] CARINA_CORE_VERSION: 7.3.15
2022-02-01 17:19:58 Log [main-1] [INFO] TSQA_beforeMethod
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/C:/Users/t928859/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

                2022-02-01 17:21:21 ProxyPool [main-1] [INFO] Starting BrowserMob proxy...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffde7f92250, pid=15332, tid=9772
#
# JRE version: Java(TM) SE Runtime Environment (14.0.2+12) (build 14.0.2+12-46)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (14.0.2+12-46, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ffde7f92250
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\TSOQA\TELUS-TSQA-TS-Internal-Client\hs_err_pid15332.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Disconnected from the target VM, address: '127.0.0.1:58824', transport: 'socket'
Process finished with exit code 1

**Web (please complete the following information):**
 - Browser [e.g. chrome]
 - Version [e.g. 97]

**Comment by akamarouski** [comment]
Fixed by #1767
