### ISSUE TITLE
emailable-report html file present skipped test scripts as failed

### ISSUE THREAD

**Issue by tvtester** [zebrunner/carina#1587]
**Describe the bug**
emailable-report.html file is not presenting valid skipped test script count. Skipped test scripts are included in the Failed count, and also details row presented as Failed instead of Skipped. Please check attached folder for it.

**Logs/Links**
[reports.zip](https://github.com/zebrunner/carina/files/7982531/reports.zip)

**Web (please complete the following information):**
 - Browser [e.g. chrome,]
 - Version [e.g. 97]

**Additional context**
- Carina V7.2.14, V7.2.13

**Comment by vdelendik** [comment]
fixed.
