### ISSUE TITLE
@CaseInsensitiveXPath is not working in 7.3.15 for Android

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/carina#1589]
**Describe the bug**
@CaseInsensitiveXPath is not working in 7.3.15 for Android
Session crashes and it is impossible to find elements after this issue.

**Logs/Links**
DriverListener [main-1] [ERROR] java.lang.IllegalArgumentException: Unable to compile ’//*[translate(@text, ‘SAVE FOR LATER’ OR @TEXT = ‘SAVE FOR LATER’, ‘save for later’ or @text = ‘save for later’)=translate(‘Save for Later’ or @text = ‘SAVE FOR LATER’, ‘SAVE FOR LATER’ OR @TEXT = ‘SAVE FOR LATER’, ‘save for later’ or @text = ‘save for later’)]’. See Cause.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html

**Mobile (please complete the following information):**
 - Device: OnePlus9
 - OS: Android
 - Appium version [e.g. 1.22.0]

**Additional context**

**Comment by maksimsarychau** [comment]
Without @CaseInsensitiveXPath elements can be found and everything is ok.

**Comment by akamarouski** [comment]
The problem is not reproducible on the Pixel XL API 32 emulator

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/carina/pull/1655

**Comment by vdelendik** [comment]
confirmed by @maksimsarychau
