### ISSUE TITLE
document ognl validation feature

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1602]
implementation: https://github.com/zebrunner/carina/pull/1593
let's provide doc in api module about usage^^^

**Comment by okamara** [comment]
Test is shifted:
<img width="752" alt="Снимок экрана 2022-02-25 в 12 28 08" src="https://user-images.githubusercontent.com/32964663/155690756-082b45e3-a923-4f24-8514-d866fc18f788.png">

**Comment by vdelendik** [comment]
it should be fixed in 2-3 min on doc site as well

**Comment by okamara** [comment]
Verified, fixed.
