### ISSUE TITLE
Update more patterns / ways for users to customize their own testcase name

### ISSUE THREAD

**Issue by ducnguyen123** [zebrunner/carina#1610]
**Customize testcase name**
In case, I want to customize my testcase name as {group_name} - {method_description} or  no pattern and I can input a String I want

**Additional context**
Carina-demo 7.3.16

**Comment by okamara** [comment]
Verified with default values via Launcher

**Comment by akamarouski** [comment]
You can use following patterns:
{test_name} - name of the test
{tuid} - TUID
{test_class} - name of the test class
{method_name} - name of the test method
{method_description} - test method description
{method_priority} - method priority
{method_thread_pool_size} - size of thread pool
{group_names} - names of the groups that the test method belongs to

Default pattern: {tuid} {map}{test_name} - {method_name}
