### ISSUE TITLE
Unable to set waitForIdleTimeout in _config file

### ISSUE THREAD

**Issue by ashuaviator1987** [zebrunner/carina#1612]
**Describe the bug**
My android application is a bit flaky, and is built on React native. Some times the code taken more 1-2 minutes to identify the element. To improve this I tried to add 
` capabilities.waitForIdleTimeout=5000` in config file.  but got error.

**Logs/Links**
Relevant log error which I got :
`Caused by: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: Invalid 'waitForIdleTimeout' setting value type. Got: java.lang.String. Expected: java.lang.Long.`

**Mobile (please complete the following information):**
 - Device: emulator
 - OS: android 11
 - Appium version : 1.22.2

**Additional context**
Application is built on react native

**Comment by okamara** [comment]
Verified,
1 case: Can't find text "Adding waitForIdleTimeout to capabilities as integer" in log file

**Comment by okamara** [comment]
Interesting, but for me works too now, I didn't change anything.
