### ISSUE TITLE
bump up to 7.6.0 TestNG

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1623]
https://github.com/cbeust/testng/blob/master/CHANGES.txt

**Comment by vdelendik** [comment]
moved to 8.x as in 7.6.0 testng moved completely to java11. in 7.x carina we should reuse latest build on java8, i.e. testng 7.5: #1696

**Comment by akamarouski** [comment]
Test on the following configuration:
carina: 8.0.0-SNAPSHOT
carina-demo branch: carina-8.x
For QA: Tests should display correctly

**Comment by okamara** [comment]
Tests failed with carina: 8.0.0-SNAPSHOT
carina-demo branch: carina-8.x; if run with branch branch: carina-8.x only too.

**Comment by okamara** [comment]
Reverified with branch: carina-8.x;, test is passed.
