### ISSUE TITLE
User not see execution logs after start Test jobs 

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#1631]
Precondition:
Install zebrunner ce
Steps:
1. Start web demo test with override fields  carina-core_version=7.3.17-SNAPSHOT,init_retry_count=2,init_retry_interval=0,selenium_url=http:///something-invalie/wd/hub
2. Verify that user can see all required logs for test job
Actual result: User not see execution logs after start Test jobs

**Comment by vdelendik** [comment]
fixed. @okamara let's use carina-demo; branch: `7.3.17` for regression testing

**Comment by okamara** [comment]
Verified with branch 7.3.17, fixed.
