### ISSUE TITLE
convert method to private in ICustomTypePage interface

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1637]
finish TODO and hide several private methods for interface default implementation

**Comment by vdelendik** [comment]
done. to test we have to run Mobile-Android-Demo-Test anywhere using `7.3.18-SNAPSHOT` carina-core_version

**Comment by okamara** [comment]
The issue is repro on customer side
<img width="1001" alt="Снимок экрана 2022-04-14 в 14 45 11" src="https://user-images.githubusercontent.com/32964663/163384432-be9b6066-ec9a-43d2-b7ff-73064a09a886.png">

**Comment by vdelendik** [comment]
changes reverted, public access to interface methods should be restored.
testing might be done using `7.3.19-SNAPSHOT`

**Comment by okamara** [comment]
Verified on demo env., fixed.
