### ISSUE TITLE
Can't switch to iframe if it's inside a component

### ISSUE THREAD

**Issue by ababrova** [zebrunner/carina#1662]
**Describe the bug**
Can't switch to iframe if it's inside a component

**Web (please complete the following information):**
 - Browser Google Chrome, 101
 - Carina Version 7.3.19

**Additional context**
Steps to repro:
1. get a component from a page
2. try to switch to iframe which is inside this component
3. do an action on the element that is inside the iframe
Actual Result: No such element By.xpath: "locator to component from step №1"

**Comment by akamarouski** [comment]
When components are described, they must follow a strict hierarchy. The search for a component comes from its location. Accordingly, if iframe components are described, then this iframe must be described as a separate class and its components must be written in it.
