### ISSUE TITLE
Web Sample: Error message in test case "org.openqa.selenium.WebDriverException: disconnected: received Inspector.detached event"

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#1689]
Env. org, carina 7.3.20
Steps:

Start Web Sample via Launcher with branch 100-200, browser Chrome version 101
1 Test case is failed with error message "org.openqa.selenium.WebDriverException: disconnected: received Inspector.detached event"
Expected: Test case is passed without errors

**Web (please complete the following information):**
 - Browser [Chrome]
 - Version [101]

**Comment by okamara** [comment]
verified, fixed.

**Comment by vdelendik** [comment]
fixed
