### ISSUE TITLE
Selenium4: reuse standard methods for full page screenshots

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1704]
https://www.softwaretestingmaterial.com/capture-screenshot-selenium-4/

think about removal of `IScreenshotRule.isAllowFullSize()` if  new method is stable enough. What about mobile?

**Comment by akamarouski** [comment]
Selenium 4 does not have a mechanism for taking screenshots of the entire page. The only option provides a separate firefox driver, but this does not apply to other drivers
