### ISSUE TITLE
doc: add info howto allow to make full size screenshots on failure

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1716]
in upcoming 7.4.21 we disabled full size screenshots generation on failure by default using `allow_fullsize_screenshot=false`.
let's document this property to let users know howto enable full size screenshoting by default on failure.
Btw, to make explicitly full size screenshot we still have:
```
public static String capture(WebDriver driver, String comment, boolean isFullSize)
```

**Comment by vdelendik** [comment]
done, find Screenshot doc article in Advanced and verify links, text etc

**Comment by okamara** [comment]
Verified here https://zebrunner.github.io/carina/advanced/screenshot/, fixed.
