### ISSUE TITLE
doc: describe integrate with zebrunner reporting using properties file

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1728]
carina manipulates a lot of properties files so we have to reorganize integration doc to proceed in the same manner

**Comment by vdelendik** [comment]
done, removed all information and screenshots about agent.yaml and as one of the most important fixed link to zebrunner documentation in `More details and examples of Environment variables, Program arguments etc can be found in the [Documentation](https://zebrunner.com/documentation/agents/testng)` sentence.

updates might be tested here: https://zebrunner.github.io/carina/integration/zebrunner/

**Comment by okamara** [comment]
Verified, fixed.
