### ISSUE TITLE
doc: replace all tricks by FAQ using question/answer manner

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1729]
FAQ format is better and can collect all most popular topics so let's refactor documentation replacing tricks in FAQ manner

**Comment by vdelendik** [comment]
done. a lot of changes applied for:
[configuration.md](https://zebrunner.github.io/carina/configuration/)
[web.nd](https://zebrunner.github.io/carina/automation/web/)
[driver.md](https://zebrunner.github.io/carina/advanced/driver/)
[program_flow.md](https://zebrunner.github.io/carina/advanced/program_flow/)

please read carefully all of them, test all kind of links and of course detect typos if any :)
@okamara, @avabishchevich ^^^

**Comment by okamara** [comment]
Duplicate "listeners" https://zebrunner.github.io/carina/configuration/
<img width="682" alt="Снимок экрана 2022-06-20 в 19 41 27" src="https://user-images.githubusercontent.com/32964663/174646998-17e7adb3-6ef4-472b-bcf9-cdaf9c1afb70.png">

**Comment by okamara** [comment]
@avabishchevich is it expected that "carina-core" link  redirected to
https://github.com/zebrunner/carina/tree/master/carina-core/src/main/resources ?

Page: https://zebrunner.github.io/carina/advanced/program_flow/
<img width="751" alt="Снимок экрана 2022-06-21 в 12 05 30" src="https://user-images.githubusercontent.com/32964663/174762720-990fdf69-bba6-4c78-a12c-7b20f3218b1a.png">

**Comment by avabishchevich** [comment]
@vdelendik ^^^ please check the comment from @okamara above

**Comment by vdelendik** [comment]
@okamara @avabishchevich, yep - that's correct. this a folder with all default properties files
