### ISSUE TITLE
deprecate and remove health_check_class and health_check_methods

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1730]
let's remove above properties and health checks functionality bettr to organize on higher CI/CD level.

**Comment by vdelendik** [comment]
in upcoming 7.4.21 marked HEALTH_CHECK_CLASS and HEALTH_CHECK_METHODS as deprecated.

**Comment by vdelendik** [comment]
send and merged PR from #1730 branch

**Comment by vdelendik** [comment]
done

**Comment by okamara** [comment]
verified on qa, fixed.
