### ISSUE TITLE
captureByRule don't make screenshot for failure

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1752]
Regression from 7.4.21 arrived with #1693 changes.
Seems like one more ErrorScreenshotRule needed but still TBD how to provide info if current test/thread/driver has an error

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/carina/pull/1759
to test I recommend to use [screenshot](https://github.com/zebrunner/carina-demo/tree/screenshot) branch of the carina-demo where I explicitly inject several important steps.

after `explicit visible area screenshot` in log we must see visible area screenshot in any below scenario
after `explicit fullsize area screenshot if allowed` in log we must see screenshot in any below scenario, but full size is aptured if `allow_fullsize_screenshot` is true

Testing scenario should cover such cases:
1. run using `auto_screenshot=true` configuration param - applicable by default
-> tests executed, visible area screenshots generated after each major action like open url, click, type etc
-> one test should be skipped with error `skipped`. closer to the end of tests we suspect to see 2 screenshots generated (one after open and 2nd before raise skip exception)
-> one test should fail with `explicit failure` error message. closer to the end 2 screenshots should be made

2. run using `auto_screenshot=false` configuration param (override via launcher):
-> no screenshot for passed test except `explicit fullsize area screenshot if allowed`
-> for skip and fail tests one visible area screenshot is generated closer to the end of test

3. run using `auto_screenshot=false; allow_fullsize_screenshot=true` configuration params:
-> no screenshot for passed test except `explicit fullsize area screenshot if allowed`
-> for skip and fail tests one fullsize screenshot is generated closer to the end of test

4. run using `auto_screenshot=true; allow_fullsize_screenshot=true` configuration params:
-> auto screenshots for visible area generated after any major action
-> for skip/fail tests before the exception full size screenshot should be generated

**Comment by okamara** [comment]
Verified on ce, and org env. case 2
