### ISSUE TITLE
Handle browserstack use-case better

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1786]
For browserstack we have to start only remote web driver, let’s adjust driver factory and if selenium_url contains hub.browserstack.com then don’t start android or ios driver.

**Comment by vdelendik** [comment]
done. if `hub.browserstack.com` detected as part of selenium url we will start mobile drivers via 
```
driver = new RemoteWebDriver(new URL(seleniumHost), capabilities);
```

**Comment by okamara** [comment]
verified by customer
