### ISSUE TITLE
investigate possibility to load/parse all config.properties inside transitive carina sub-modules

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1793]
to start splitting modules to independent projects carina-crypto looks the best candidate. making this movement we support more crypto algorithms etc.
the only blocker on this step is our operation with config.properties which is global one and located only in `carina-core/src/main/resources`.

we have to reorganize code a little bit using better classloader or via transitive maven resource dependencies to be able to split each param inside independent project and be able to load and combine on R.init

**Comment by okamara** [comment]
Verified, no VNC session for web test.
