### ISSUE TITLE
How to pass properties files an argument to curl command for running GitHub Actions

### ISSUE THREAD

**Issue by tvtester** [zebrunner/carina#1801]
Hello, We're having the GitHub Actions to run the test scripts. And we're using the curl command to execute that GitHub Actions from outside of our project. At this moment, GitHub Action uses the _config.properties and _testdata.properties file which is store in the repo/branch.
Is there any way to pass the those two properties file as argument to curl command, so GitHub Action can use that property files instead of stored one from branch/repo?

i.e.
curl -XPOST -u "Username:KEY" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" {{repoUrl}}/actions/workflows/maven.yml/dispatches --data '{"ref": "{{branchName}}"}'

**Comment by akamarouski** [comment]
It is possible to add/override parameters using system/environment.
