### ISSUE TITLE
API : Unable to truncate values in carina framework with ValidateResponse method

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/carina#1816]
I am stuck at one API response verification. can you please help me here
When I am running API, I am getting the below responses(Expected are already saved in the system)

Scenario 1 :

Actual: 6.38502265600041**4**
Expected: 6.38502265600041**5**

Scenario 2 :

Actual: 6.3850226560004**3**
Expected: 6.3850226560004**29**

Can you tell me how to handle this?

**Comment by brutskov** [comment]
@prasadjshimpi or using the `predicate` wildcard (see https://zebrunner.github.io/carina/automation/api/#wildcards)
