### ISSUE TITLE
Auto-Download-Test, Web-Demo-Test failed Unsupported browser in Full regression for carina-core 7.4.26

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#1850]
carina-core 7.4.26
steps:
1. Run Full regression
Actual result: Auto-Download-Test, Web-Demo-Test failed 
with error message "TEST [GSM arena web tests - testCompareModels] FAILED at [09:22:14 2022-09-28] - Unsupported browser:  chrome" or "Unsupported browser:  firefox"
<img width="1371" alt="Снимок экрана 2022-09-29 в 00 51 09" src="https://user-images.githubusercontent.com/32964663/192897088-a723dbba-f105-4f74-905e-3ea9a2a4ff62.png">

<img width="1375" alt="Снимок экрана 2022-09-29 в 00 51 19" src="https://user-images.githubusercontent.com/32964663/192897110-21939166-8c8c-4e5c-8d8e-5788b88e27f6.png">

**Comment by akamarouski** [comment]
More info: capabilities are overwritten incorrectly (an extra space is added)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/98826957/192968594-1cddcdef-62d3-4106-b375-11abd741a924.png">

**Comment by akamarouski** [comment]
Refers to carina-demo. Moved
