### ISSUE TITLE
taking a screenshot takes a minute

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#1857]
**Logs/Links**
21.01.18 Using open Channel ... for GET '/wd/hub/session/.../screenshot'
21.02.18 Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content:...)
GET /wd/hub/session/.../screenshot HTTP/1.1
User-Agent: selenium/4.4.0
...

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 500 Internal Server Error
...

**Web:**
 - Browser Chrome

**Additional context**
Carina version: 8.0.0

**Comment by okamara** [comment]
Verified, fixed.
