### ISSUE TITLE
callApiExpectSuccess method check not only status code, but also statusLine

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#1910]
statusLine hardcoded in HttpResponseStatusType enum as message. Not all api should response with such hardcoded messages.
Maybe @SuccessfulHttpStatus annotation should take code and message (optionally) separately

**Comment by okamara** [comment]
Run regression and smoke. Created ticket for add test case in carina-demo to check this method https://github.com/zebrunner/carina-demo/issues/309
