### ISSUE TITLE
Issue with capture screenshot in web test:"Unable to capture screenshot due to the WebDriverException!"

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#1911]
**Describe the bug**
Web demo Test case is failed, screenshot was not added due to error"Unable to capture screenshot due to the WebDriverException!"

log:
`TEST [GSM arena web tests - testModelSpecs] FAILED at [11:06:39 2022-10-28] - unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=106.0.5249.61)
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: '462de183c9b3', ip: '172.18.0.12', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1088-aws', java.version: '11.0.12'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [7f7dd995c03fb9c818652a790727be93, clickElement {id=1669100e-b773-4290-9710-c397dc0d9be4}]`
<img width="910" alt="Снимок экрана 2022-10-28 в 14 24 31" src="https://user-images.githubusercontent.com/32964663/198579075-b7c3a503-10ae-4d67-969b-536f8aa251cb.png">

**Comment by akamarouski** [comment]
wont fix
