### ISSUE TITLE
add FAQ about location of mobile-specific methods

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#1913]

**Comment by okamara** [comment]
Verified, links redirected to page not found 
[IMobileUtils](https://github.com/zebrunner/carina/blob/master/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java) - contains methods for interacting with both IOS and Android devices
[IAndroidUtils](https://github.com/zebrunner/carina/blob/master/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java), [AndroidService](https://github.com/zebrunner/carina/blob/master/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidService.java) - contains methods for interacting with Android devices only
[IOSUtils](https://github.com/zebrunner/carina/blob/master/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/ios/IOSUtils.java) - contains methods for interacting with IOS devices only

**Comment by akamarouski** [comment]
assigned to @dmtgrinevich

**Comment by okamara** [comment]
Verified, fixed
