### ISSUE TITLE
Localized locators don't work for IOS

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#1949]
**Describe the bug**
createExtendedBy method of LocalizedAnnotations should understand not only By.IosClassChain, but also AppiumBy.iosClassChain and so on. Now the absence of this logic leads to the fact that the locator is overwritten with the original

**Mobile (please complete the following information):**
 - Carina version: 8.0.2

**Comment by okamara** [comment]
verified by @akamarouski
