### ISSUE TITLE
missing video for android (mcloud)

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#1965]
Carina 8.0.3-SNAPSHOT

**Comment by akamarouski** [comment]
for redroid invalid - video exists

**Comment by vdelendik** [comment]
root cause: https://github.com/zebrunner/mcloud-grid/issues/83

**Comment by akamarouski** [comment]
solved in https://github.com/zebrunner/mcloud-grid/issues/83

**Comment by okamara** [comment]
repro issue

**Comment by okamara** [comment]
fixed
