### ISSUE TITLE
ExtendedWebElement#isElementPresent should not throw StaleElementReferenceException

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#2035]

**Comment by littleclay** [comment]
@akamarouski

Hello! I was going to try to push a fix for this but was not sure of what the expected behavior should be if the the underlying `waitUntil` call in `ExtendedWebElement` throws a `StaleElementReferenceException`. Should it throw a different exception, return false, etc?

**Comment by akamarouski** [comment]
Hello, @littleclay 
Since this is a method for checking the state of an element, if the element is in the _Stale_ state, then it means that it is not exists on the page already, so we should return false.
The error is most likely thrown by the `visibilityOf` method of `ExpectedConditions` class, so you need maybe try to use something like inverted `invisibilityOf` condition.

**Comment by littleclay** [comment]
https://github.com/zebrunner/carina/pull/2044

**Comment by okamara** [comment]
Verified by automation tests
