### ISSUE TITLE
Need a way to install chrome extension programmatically on carina 8 with selenium 4

### ISSUE THREAD

**Issue by SergeiZagriychuk** [zebrunner/carina#2053]
Right now test which installs the extension fails. But at the same time it successfully works with carina 7 (which uses selenium 3)
That is how test sets the extension before method:

`public void startDriverWithExtension() {
        // To get access browser's sessions should contain Mod Header extension
        // for installing headers with Google OIDC token
        DesiredCapabilities cap = new ChromeCapabilities().getCapability("default");
        ChromeOptions options = new ChromeOptions();
        options.addEncodedExtensions(initExtensionFromFile());
        cap.setCapability(ChromeOptions.CAPABILITY, options);
        getDriver("default", cap);
    }`

And file contains extension in encoded state

**Comment by SergeiZagriychuk** [comment]
No changes needed in carina at this point.
code for setting of extension with selenium 4 should be next:
```
ChromeOptions cap = new ChromeCapabilities().getCapability("default");
        cap.addEncodedExtensions(initExtensionFromFile());
        getDriver("default", cap);
```

**Comment by vdelendik** [comment]
@akamarouski, let's document it with example for concrete extension in web FAQ block: https://zebrunner.github.io/carina/automation/web/#faq
