### ISSUE TITLE
Issue in docs

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#2063]
Steps:
1. Open carina docs https://zebrunner.github.io/carina/advanced/proxy/
2. Scroll down and verify that all numbers and their orders are correct on the whole page
Actual result: Ordering not correct and user can see 1,1 numbers for points
Expected result:Ordering is correct and user can see 1,2,3 numbers for points

<img width="746" alt="Снимок экрана 2023-02-16 в 18 45 53" src="https://user-images.githubusercontent.com/32964663/219416879-4c8436a3-4521-458c-8bb5-99a1cba3c5d5.png">

<img width="739" alt="Снимок экрана 2023-02-16 в 18 45 46" src="https://user-images.githubusercontent.com/32964663/219417712-ceef3d33-6b37-4899-8819-c9183fbbdc6e.png">

**Comment by akamarouski** [comment]
assigned to @dmtgrinevich

**Comment by okamara** [comment]
Verified, fixed
