### ISSUE TITLE
java.util.concurrent.TimeoutException when use driver.navigate().back()

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#2081]
TEST FAILED - java.util.concurrent.TimeoutException
Build info: version: '4.4.0', 
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [ goBack {}]
org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:57)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.back(RemoteWebDriver.java:1021)
jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.openqa.selenium.support.decorators.WebDriverDecorator.call(WebDriverDecorator.java:247)
org.openqa.selenium.support.decorators.DefaultDecorated.call(DefaultDecorated.java:48)
org.openqa.selenium.support.decorators.WebDriverDecorator.lambda$createProxy$0(WebDriverDecorator.java:309)
net.bytebuddy.renamed.java.lang.Object$ByteBuddy$GW5hKa2z.back(Unknown Source)
***

**Comment by dmtgrinevich** [comment]
Can't reproduce
