### ISSUE TITLE
list all independent carina repositories in the README.md

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#2184]
As we split carina into different repos we don't know exact sub-modules anymore.
let's list somewhere on top of readme all submodules (projects)

**Comment by akamarouski** [comment]
@okamara wait until PR https://github.com/zebrunner/carina/pull/2182 is merged

**Comment by okamara** [comment]
![Image](https://github.com/zebrunner/carina/assets/32964663/3b3241b5-c634-41c0-9a8a-4f3c04afc917)

**Comment by akamarouski** [comment]
@okamara please close this issue and move https://github.com/zebrunner/carina/issues/2184#issuecomment-1551078047 to the https://github.com/zebrunner/carina/issues/2194

**Comment by vdelendik** [comment]
done, @okamara - review above comment
