### ISSUE TITLE
let's add example of the smooth migration from crypto_key_file to crypto_key_value

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#2195]
https://zebrunner.github.io/carina/migration/#redesigned-the-encryption-process

Let's add code snippet which can read data from historical `crypto_key_file` and put into the env var `crypto_key_value`.
And note that we recommend to move it completely to env vars in secured way

**Comment by akamarouski** [comment]
@okamara wait until PR https://github.com/zebrunner/carina/pull/2182 is merged

**Comment by okamara** [comment]
verified, fixed.
