### ISSUE TITLE
remove `:` in the doc header

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#2196]
https://zebrunner.github.io/carina/migration/#project-side-dependency-requirements has a colon symbol et the end:
```
Project side dependency requirements:
```

let's remove it because all the rest doesn't have it.

**Comment by akamarouski** [comment]
@okamara wait until PR https://github.com/zebrunner/carina/pull/2182 is merged

**Comment by okamara** [comment]
verified
