### ISSUE TITLE
listeners ignore 500 error from server and wait till the end of read_timeout

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#2211]
after several debug sessions we can confirm that esg and I suppose mcloud grid return valid error to carina with exact failure message.
but in latest versions (I believe starting from selenium 4) we wait till the end of timeout (600 or 660s) and raise timeout exception.

we have to review again listener logic and don't hide error from the server (500 as minimal)

**Comment by akamarouski** [comment]
Fixed during refactoring. Possible cause: netty-codec dependency in the carina-webdriver module. (removed)
