### ISSUE TITLE
7.4.x: add support of the mcloud-grid:2.2 slotCapabilitites parser

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#2232]
"zebrunner:slotCapabilities" should be parsed now from grid response.
let's keep in 7.4.x both ways... it is enough to provide snapshot as globally movement on to the carina 1.x is needed.

**Comment by akamarouski** [comment]
carina-core version: 7.4.28.CAPS-SNAPSHOT

**Comment by akamarouski** [comment]
wontfix. It is recommended to update the carina-core version to 1.2.7+
