### ISSUE TITLE
Testing Windows applications with Carina Framework and Selenium 4

### ISSUE THREAD

**Issue by rhapsodyman** [zebrunner/carina#2241]
WinAppDriver that is used by the framework doesn't not support Selenium4. 
And there is no timeline when the support will be added.
https://github.com/microsoft/WinAppDriver/issues/1839

Any ideas how to do the testing, any alternatives to replace WinAppDriver ?

**Comment by akamarouski** [comment]
Hi, @rhapsodyman 
Check Appium Windows Driver https://github.com/appium/appium-windows-driver#usage

**Comment by akamarouski** [comment]
You need to set `capabilities.platformName=Windows` to the `_config.properties` for creating `WindowsDriver` when you call `getDriver` method.
You can also use `WindowsFindBy`, `WindowsFindBys` and other appium annotations for finding elements
