### ISSUE TITLE
Implement API call fluentWait analogue with timeout and polling interval

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#330]
Sometimes we should do a lot of API calls  waiting for particular artifact in response.
For now it is organized on a project level and as side effect we do a lot of useless log_all_json logging operations.

So we suggest to implement API call response waiter with a timeout and polling interval and ability to log only last request and response into the log

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/carina/pull/1609
to be able to verify need to write/update any api tests in carina-demo: https://github.com/zebrunner/carina-demo/issues/217

@okamara, please review carina doc site in automation->api page `#### Repeating API calling with the condition`. actual changes you can find in above pull request

**Comment by okamara** [comment]
Verified, fixed.
