### ISSUE TITLE
Support for @FindBys and @FindAll annotations

### ISSUE THREAD

**Issue by Kavyahr** [zebrunner/carina#672]
ExtendedFieldDecorator handles only those fields which has @FindBy and @FindAI annotations now, please add the support for @FindAll and @FindBys annotations so that any variations in locators can be handled.

This featured is needed as the elements inside a component are not same across all the pages in the applications.

**Comment by akamarouski** [comment]
Added support of all Selenium and Appium annotations

**Comment by okamara** [comment]
will be verified in auto test in carina-demo
