### ISSUE TITLE
add soap test example with valid documentation steps

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#739]
need working example of the public soap testing via carina and simple guide about recommended approach

**Comment by vdelendik** [comment]
need to fix conflicts and merge: https://github.com/qaprosoft/carina-demo/pull/66

**Comment by vdelendik** [comment]
soap moved into independent repo: https://github.com/qaprosoft/carina-soap
need only document steps

**Comment by okamara** [comment]
Verified https://github.com/zebrunner/carina-soap
